### ISSUE TITLE
Polygon color

### ISSUE THREAD

**Issue by WaaaghNL** [MichelGerding/Homeassistant-polygonal-zones-addon#2]
Love the work you did! But is there a way to change the color of a polygon when creating them? They are light green and are a bit hard to see in a forrest area or town. It can be me but a added a screenshot as an example. i like the blue they get after saving and a page reload.

Some idea's for the green, a bit less transparency and a thick dark green border? Or a color thats not used in the map like purple?

![image](https://github.com/user-attachments/assets/c4656348-b2b6-4d6f-ba7e-b977a4f71e5c)

**Comment by MichelGerding** [comment]
i did not find a way to easily control the opacity of the infill. so i added the option to configure the colour using the add-on configuration. it supports all css colours so you can use rgb, hex, colour names, etc. the default is now set to purple.

**Comment by WaaaghNL** [comment]
Updated the add-on and see the nice purple shapes come to life! Thank you
